spring:
  profiles:
    active:
      - dev
    default: local

  application:
    name: backend-spring-boot-project

  servlet:
    multipart:
      max-file-size: 200MB
      file-size-threshold: 2KB

  mail:
    host: smtp.gmail.com
    port: 587
    username: yash.sanjay.raghuwanshi@gmail.com
    password: qxwd mzii pyma fncu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  output:
    ansi:
      enabled: always

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
    java:
      enabled: true
    build:
      enabled: true
    os:
      enabled: true

#custom properties
info:
  app:
    name: backend-spring-boot-project
    version: v0.0.1

#my:
#  server:
#    name: backend-server
#    port: 8888

logging:
  level:
    root: info
    org.hibernate.SQL: info
    org.springframework.web: debug


