server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productsdb?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect:
          - org.hibernate.dialect.MySQL8Dialect
      format_sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true